run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  staticcheck:
    checks:
      - all
      - -SA1029

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
