version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - amanah-network
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - amanah-network
    volumes:
      - redis-data:/data

  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - amanah-network
    depends_on:
      - app

networks:
  amanah-network:
    driver: bridge

volumes:
  redis-data: